/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MABGui;
import javax.swing.JFileChooser;
import static MABGui.MyAdressBookWindow.colnames;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;
import mabproject.Account;
import mabproject.AccountCollection;
import mabproject.AdressBook;
import mabproject.AdressBookCollection;
import mabproject.Contact;
import mabproject.MABProject;

/**
 *
 * @author mac
 */
public class HomePage extends javax.swing.JFrame {
    public static AdressBookCollection adressBooks = new AdressBookCollection();
    public static AccountCollection accounts = new AccountCollection();
    public static AdressBook MoroccanAdressBook = new AdressBook("Moroccan Adress Book");
    public static String pathToHome = System.getProperty("user.home") + File.separator + File.separator +"MAB";
    /**
     * Creates new form HomePage
     */
    public HomePage() {
       setTitle("MAB Project");
        setLayout(new FlowLayout()); 
        try {
            MoroccanAdressBook.load(pathToHome + File.separator + "MAB.ser");
        } catch (Exception ex) {
            System.out.println("trying to load");
            //JOptionPane.showMessageDialog(this, "Backup File not found, it will be created in your home folder", "Info", JOptionPane.INFORMATION_MESSAGE);
            new File(pathToHome).mkdir();
            
        }
        initComponents();
        this.setResizable(false);
       this.setLocationRelativeTo(null);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        LoginButton = new javax.swing.JButton();
        SigninButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ViewMABButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SaveButton = new javax.swing.JMenuItem();
        Print = new javax.swing.JMenuItem();
        QuitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MAB Project");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(427, 240, 427, 240));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(427, 240));

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setFont(new java.awt.Font("Apple Braille", 1, 13)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(51, 51, 51));
        LoginButton.setText("LOGIN");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        SigninButton.setBackground(new java.awt.Color(255, 255, 255));
        SigninButton.setFont(new java.awt.Font("Apple Braille", 1, 13)); // NOI18N
        SigninButton.setForeground(new java.awt.Color(51, 51, 51));
        SigninButton.setText("SIGN IN");
        SigninButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d2.jpg"))); // NOI18N

        ViewMABButton.setBackground(new java.awt.Color(255, 255, 255));
        ViewMABButton.setForeground(new java.awt.Color(51, 51, 51));
        ViewMABButton.setText("View Moroccan AdressBook");
        ViewMABButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMABButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        SaveButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save.png"))); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jMenu1.add(SaveButton);

        Print.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Download.png"))); // NOI18N
        Print.setText("Export as PDF");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jMenu1.add(Print);

        QuitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        QuitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Abort.png"))); // NOI18N
        QuitMenuItem.setText("Quit");
        QuitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(QuitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/About.png"))); // NOI18N
        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(SigninButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewMABButton)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SigninButton)
                    .addComponent(LoginButton)
                    .addComponent(ViewMABButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 738, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        close();
        LoginPage lgp = new LoginPage();
        lgp.setVisible(true);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SigninButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninButtonActionPerformed
        // TODO add your handling code here:
        close();
        AddAccountWindow addAccount = new AddAccountWindow();
        addAccount.setVisible(true);
        
    }//GEN-LAST:event_SigninButtonActionPerformed

    private void QuitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_QuitMenuItemActionPerformed

    private void ViewMABButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMABButtonActionPerformed
        // TODO add your handling code here:
        close();
        MABadressBook mb = new MABadressBook();
        mb.setVisible(true);
    }//GEN-LAST:event_ViewMABButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        try {
            MoroccanAdressBook.save(pathToHome + File.separator + File.separator + "MAB.ser");
            System.out.println("ana f save, try homepage");
        } catch (IOException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(HomePage.this, "" + "The PDF file was created." ,"Moroccan Address Book", JOptionPane.INFORMATION_MESSAGE);
        List <Contact> l = MoroccanAdressBook.getAdressBook();
        ListIterator<Contact> iter = l.listIterator();
        String[] data = new String[l.size()];
        if (iter.hasNext()) {
            int i = 0;
            while (iter.hasNext()) {
                Contact ct = iter.next();
                data[i] = ct.getLastName()+" "+ ct.getFirstName()+" "+ct.getAdress()+" "+ct.getCity()+" "+ct.getPostalCode()+ " "+ct.getPhoneNumber();
                
                i++;
            }
            
        }
        try {
            File file = new File("Printed_Moroccan_Address_Book.pdf");
            FileOutputStream fileout = new FileOutputStream(file);
            Document document = new Document();
                
            PdfWriter.getInstance((com.itextpdf.text.Document) document, fileout);
            document.open();
            Paragraph paragraph = new Paragraph();
            paragraph.add("Moroccan Address Book:\n");
            paragraph.add("\n");
            for(int i = 0; i < l.size(); i++){
                int j=i+1;
                paragraph.add(data[i]);
                paragraph.add("\n");
             }
            paragraph.setAlignment(HEIGHT);
            document.add(paragraph);

            document.close();
                        
	} catch (FileNotFoundException e) {
			e.printStackTrace();
	} catch (DocumentException e) {
			e.printStackTrace();
	}

        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_PrintActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(HomePage.this,"About MAB:\n"
                + "This project has been done by Manal Hamdi and Mehdi Laziri under the supervision of Dr. Falah\n"
                
                , "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JMenuItem Print;
    private javax.swing.JMenuItem QuitMenuItem;
    private javax.swing.JMenuItem SaveButton;
    private javax.swing.JButton SigninButton;
    private javax.swing.JButton ViewMABButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        close();
    }   
    private void close() {
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/guis/icons/Groupon.png")));
    }
}
