/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MABGui;
import static MABGui.HomePage.MoroccanAdressBook;
import static MABGui.HomePage.adressBooks;
import static MABGui.MyAdressBookWindow.colnames;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.ListIterator;
import javax.swing.table.DefaultTableModel;
import mabproject.AdressBook;
import mabproject.Contact;
import mabproject.LastNameComparator;
import mabproject.PostalCodeComparator;

/**
 *
 * @author mac
 */
public class MABadressBook extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form MABadressBook
     */
    public MABadressBook() {
        initComponents();
        model = new DefaultTableModel();
        Table.setModel(model);
        load();
        this.setLocationRelativeTo(null);
    }
     public void load() {
        AdressBook valid = MoroccanAdressBook;
        
        List<Contact> results = MoroccanAdressBook.getAdressBook(); //results is the list of contacts in the adress Books
        ListIterator<Contact> iter = results.listIterator();
        if (iter.hasNext()) {
            Object[][] data = new Object[results.size()][colnames.length];
            int i = 0;
            while (iter.hasNext()) {
                Contact ct = iter.next();
                data[i][0] = ct.getLastName()+" "+ ct.getFirstName();
                data[i][1] = ct.getAdress();
                data[i][2] = ct.getCity();
                data[i][3] = ct.getPostalCode();
                data[i][4] = ct.getPhoneNumber();
                i++;
            }
            model.setDataVector(data, colnames);
        }
        else {
            model.setDataVector(null, colnames);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        SortLNButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jScrollBar2 = new javax.swing.JScrollBar();
        SortLNButton = new javax.swing.JButton();
        SortPCButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        SortLNButton1.setText("Sort by Last Name");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Adress", "City", "Postal Code", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        SortLNButton.setText("Sort by Last Name");
        SortLNButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortLNButtonActionPerformed(evt);
            }
        });

        SortPCButton.setText("Sort by Postal Code");
        SortPCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortPCButtonActionPerformed(evt);
            }
        });

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(SortLNButton)
                        .addGap(18, 18, 18)
                        .addComponent(SortPCButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SortLNButton)
                            .addComponent(SortPCButton))
                        .addContainerGap())
                    .addComponent(jScrollBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SortPCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortPCButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel) Table.getModel();
        model2.setRowCount(0);
         loadSortedByPostalCode();
    }//GEN-LAST:event_SortPCButtonActionPerformed
     private void loadSortedByPostalCode (){
        AdressBook valid = MoroccanAdressBook;
        PostalCodeComparator comp = new PostalCodeComparator();
        valid.SortContactLastName(comp);
        List<Contact> results = valid.getAdressBook(); //results is the list of contacts in the adress Books
        ListIterator<Contact> iter = results.listIterator();
        if (iter.hasNext()) {
            Object[][] data = new Object[results.size()][colnames.length];
            int i = 0;
            while (iter.hasNext()) {
                Contact ct = iter.next();
                System.out.println(ct.getLastName()+" "+ ct.getFirstName());
                data[i][0] = ct.getLastName()+" "+ ct.getFirstName();
                data[i][1] = ct.getAdress();
                data[i][2] = ct.getCity();
                data[i][3] = ct.getPostalCode();
                data[i][4] = ct.getPhoneNumber();
                i++;
            }
            model.setDataVector(data, colnames);
        }
        else {
            model.setDataVector(null, colnames);
        }
    }
    private void SortLNButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortLNButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel) Table.getModel();
        model2.setRowCount(0);
        loadSortedByLastName();
    }//GEN-LAST:event_SortLNButtonActionPerformed
    private void loadSortedByLastName (){
        AdressBook valid = MoroccanAdressBook;
        LastNameComparator comp = new LastNameComparator();
        valid.SortContactLastName(comp);
        List<Contact> results = valid.getAdressBook(); //results is the list of contacts in the adress Books
        ListIterator<Contact> iter = results.listIterator();
        if (iter.hasNext()) {
            Object[][] data = new Object[results.size()][colnames.length];
            int i = 0;
            while (iter.hasNext()) {
                Contact ct = iter.next();
                System.out.println(ct.getLastName()+" "+ ct.getFirstName());
                data[i][0] = ct.getLastName()+" "+ ct.getFirstName();
                data[i][1] = ct.getAdress();
                data[i][2] = ct.getCity();
                data[i][3] = ct.getPostalCode();
                data[i][4] = ct.getPhoneNumber();
                i++;
            }
            model.setDataVector(data, colnames);
        }
        else {
            model.setDataVector(null, colnames);
        }
    }
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        close();
        HomePage pp = new HomePage();
        pp.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MABadressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MABadressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MABadressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MABadressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MABadressBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton SortLNButton;
    private javax.swing.JButton SortLNButton1;
    private javax.swing.JButton SortPCButton;
    private javax.swing.JTable Table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private void close() {
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}
